name: Java CI

on:
  push:
#   tags:
#      - v*

jobs:
  build:
    name: Deploy release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Package the jar archive
        run: mvn -B package

      - name: Generate the javadoc
        run: mvn -B javadoc:javadoc
